# Generated by Django 5.0.2 on 2024-02-21 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'verbose_name': 'Business'},
        ),
        migrations.RemoveField(
            model_name='business',
            name='organization_name',
        ),
        migrations.AddField(
            model_name='business',
            name='business_name',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='business',
            name='is_registered',
            field=models.IntegerField(choices=[(0, 'Not Registered'), (1, 'Registered'), (2, 'Registration in process')], default=0),
        ),
        migrations.AddField(
            model_name='business',
            name='phone_number',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
