# Generated by Django 5.0.2 on 2024-02-23 20:19

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.IntegerField(choices=[(1, 'One Day Trial'), (2, 'Daily'), (3, 'Weekly'), (4, 'Monthly')])),
            ],
        ),
        migrations.CreateModel(
            name='TBUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile_picture', models.TextField()),
                ('phone_number', models.CharField(max_length=10)),
                ('client_type', models.IntegerField(choices=[(0, 'User'), (1, 'Business')], default=0)),
                ('is_registered', models.BooleanField(default=False)),
                ('shipping_address', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'TBUser',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='TiffinItemList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField()),
                ('shipping_address', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=10)),
                ('payment_method', models.IntegerField(choices=[(0, 'Credit Card'), (1, 'Debit Card'), (2, 'Cash'), (3, 'Interac')], default=0)),
                ('status', models.IntegerField(choices=[(0, 'Delivered'), (1, 'Order Placed'), (2, 'Shipped'), (3, 'Cancelled')], default=0)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_dashboard.tbuser')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user_dashboard.tbuser')),
            ],
        ),
        migrations.CreateModel(
            name='Tiffin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiffin_name', models.CharField(max_length=50)),
                ('tiffin_description', models.TextField()),
                ('image', models.TextField()),
                ('meal_type', models.IntegerField(choices=[(0, 'VEG'), (1, 'NON-VEG'), (2, 'VEGAN')], default=0)),
                ('calories', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('avg_rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('free_delivery_eligible', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('business_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_dashboard.tbuser')),
                ('schedule_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user_dashboard.schedule')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user_dashboard.tbuser')),
                ('tiffin', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user_dashboard.tiffin')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_dashboard.orders')),
                ('tiffin_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user_dashboard.tiffin')),
            ],
        ),
        migrations.CreateModel(
            name='TiffinContents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiffinitem_description', models.TextField()),
                ('quantity', models.IntegerField()),
                ('quantity_metric', models.CharField(max_length=50)),
                ('tiffin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_dashboard.tiffin')),
                ('tiffinitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_dashboard.tiffinitemlist')),
            ],
        ),
    ]
