# Generated by Django 5.0.2 on 2024-03-15 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiffin',
            name='avg_rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=2),
        ),
        migrations.AlterField(
            model_name='tiffin',
            name='calories',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='tiffin',
            name='meal_type',
            field=models.IntegerField(blank=True, choices=[(0, 'VEG'), (1, 'NON-VEG'), (2, 'VEGAN')], default=0),
        ),
        migrations.AlterField(
            model_name='tiffin',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='tiffin',
            name='tiffin_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tiffincontent',
            name='tiffinitem_description',
            field=models.TextField(blank=True),
        ),
    ]
