# Generated by Django 5.0.2 on 2024-03-15 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0002_alter_tiffin_avg_rating_alter_tiffin_calories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiffin',
            name='meal_type',
            field=models.IntegerField(blank=True, choices=[(0, 'VEG'), (1, 'NON-VEG'), (2, 'VEGAN')]),
        ),
    ]
