# Generated by Django 5.0.2 on 2024-03-18 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0004_alter_tiffin_meal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiffin',
            name='meal_type',
            field=models.IntegerField(blank=True, choices=[(0, 'VEG'), (1, 'NON-VEG'), (2, 'VEGAN')]),
        ),
    ]
